/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    courses: Course;
    'course-sessions': CourseSession;
    pages: Page;
    trips: Trip;
    albums: Album;
    events: Event;
    signups: Signup;
    orders: Order;
    'payment-attempts': PaymentAttempt;
    'payment-events': PaymentEvent;
    outbox: Outbox;
    contacts: Contact;
    newsletter: Newsletter;
    redirects: Redirect;
    'import-runs': ImportRun;
    'audit-events': AuditEvent;
    media: Media;
    documents: Document;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-sessions': CourseSessionsSelect<false> | CourseSessionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    trips: TripsSelect<false> | TripsSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    signups: SignupsSelect<false> | SignupsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payment-attempts': PaymentAttemptsSelect<false> | PaymentAttemptsSelect<true>;
    'payment-events': PaymentEventsSelect<false> | PaymentEventsSelect<true>;
    outbox: OutboxSelect<false> | OutboxSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Każdy produkt ma ten sam adres co dziś: /{ID}-{nazwa}.html
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  searchText?: string | null;
  vmId: number;
  /**
   * Np. 3625-maska-soprastek-corona
   */
  slug: string;
  category: number | Category;
  categories?: (number | Category)[] | null;
  categoryName?: string | null;
  manufacturer?: string | null;
  sku?: string | null;
  priceCents?: number | null;
  salePriceCents?: number | null;
  taxRate?: number | null;
  price: number;
  /**
   * Puste = brak promocji
   */
  salePrice?: number | null;
  stock?: number | null;
  images?: (number | Media)[] | null;
  short?: string | null;
  /**
   * Treść HTML ze źródła; przed publikacją aplikacja usuwa niebezpieczne elementy.
   */
  body?: string | null;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        label: string;
        sku?: string | null;
        legacyKey?: string | null;
        priceCents?: number | null;
        stock?: number | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  warranty?: string | null;
  published?: boolean | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  importedAt?: string | null;
  sourceUpdatedAt?: string | null;
  legacyPath?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Np. 80-maski-i-fajki — adres /80-maski-i-fajki.html zostaje taki sam jak dziś
   */
  slug: string;
  /**
   * Zachowane przy migracji, żeby adresy i pozycje w Google nie zmieniły się
   */
  vmId?: number | null;
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  order?: number | null;
  published?: boolean | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  importedAt?: string | null;
  sourceUpdatedAt?: string | null;
  legacyPath?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  name: string;
  /**
   * Adres: /kursy-nurkowania/{slug}.html — bez zmian względem obecnej strony
   */
  slug: string;
  org?: ('PADI' | 'IANTD' | 'TDI/SDI' | 'Freediving' | 'Inne') | null;
  level?: ('intro' | 'basic' | 'advanced' | 'rescue' | 'pro' | 'specialty') | null;
  maxDepth?: number | null;
  nextDate?: string | null;
  price?: number | null;
  minAge?: number | null;
  lead?: string | null;
  /**
   * Treść HTML ze źródła; przed publikacją aplikacja usuwa niebezpieczne elementy.
   */
  body?: string | null;
  image?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  sections?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  includes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  order?: number | null;
  published?: boolean | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  importedAt?: string | null;
  sourceUpdatedAt?: string | null;
  legacyPath?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-sessions".
 */
export interface CourseSession {
  id: number;
  title: string;
  course: number | Course;
  startsAt: string;
  endsAt?: string | null;
  location?: string | null;
  priceCents?: number | null;
  /**
   * Puste pole oznacza brak potwierdzonego limitu. Formularz zbiera zgłoszenia; nie deklaruje wolnych miejsc.
   */
  capacity?: number | null;
  reserved?: number | null;
  published?: boolean | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  importedAt?: string | null;
  sourceUpdatedAt?: string | null;
  legacyPath?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  path: string;
  kind: 'page' | 'news' | 'report' | 'legal';
  lead?: string | null;
  /**
   * Treść HTML ze źródła; przed publikacją aplikacja usuwa niebezpieczne elementy.
   */
  body?: string | null;
  image?: (number | null) | Media;
  album?: (number | null) | Album;
  publishedAt?: string | null;
  /**
   * Strona pokazuje produkty wskazane poniżej, w podanej kolejności.
   */
  listing?: boolean | null;
  listingCategory?: (number | null) | Category;
  listingProducts?: (number | Product)[] | null;
  listingMissing?:
    | {
        title: string;
        legacyPath?: string | null;
        id?: string | null;
      }[]
    | null;
  listingFrom?: number | null;
  listingTo?: number | null;
  listingTotal?: number | null;
  listingLinks?:
    | {
        label: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  importedAt?: string | null;
  sourceUpdatedAt?: string | null;
  legacyPath?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: number;
  title: string;
  path: string;
  description?: string | null;
  date?: string | null;
  photos?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  importedAt?: string | null;
  sourceUpdatedAt?: string | null;
  legacyPath?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips".
 */
export interface Trip {
  id: number;
  title: string;
  path: string;
  location?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  priceCents?: number | null;
  lead?: string | null;
  /**
   * Treść HTML ze źródła; przed publikacją aplikacja usuwa niebezpieczne elementy.
   */
  body?: string | null;
  image?: (number | null) | Media;
  album?: (number | null) | Album;
  published?: boolean | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  importedAt?: string | null;
  sourceUpdatedAt?: string | null;
  legacyPath?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  startsAt: string;
  endsAt?: string | null;
  location?: string | null;
  path?: string | null;
  /**
   * Treść HTML ze źródła; przed publikacją aplikacja usuwa niebezpieczne elementy.
   */
  body?: string | null;
  courseSession?: (number | null) | CourseSession;
  trip?: (number | null) | Trip;
  published?: boolean | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  importedAt?: string | null;
  sourceUpdatedAt?: string | null;
  legacyPath?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signups".
 */
export interface Signup {
  id: number;
  course: number | Course;
  session?: (number | null) | CourseSession;
  privacyAccepted: boolean;
  consentVersion?: string | null;
  reservationExpiresAt?: string | null;
  confirmationTokenHash?: string | null;
  deduplicationKey?: string | null;
  emailConfirmedAt?: string | null;
  reservationReleased?: boolean | null;
  courseName?: string | null;
  name: string;
  email: string;
  phone: string;
  message?: string | null;
  status?: ('new' | 'contacted' | 'enrolled' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  number: string;
  customerName: string;
  email: string;
  phone?: string | null;
  address?: string | null;
  items?:
    | {
        product: number | Product;
        productName: string;
        sku?: string | null;
        variantId?: string | null;
        variant?: string | null;
        qty: number;
        price: number;
        unitPriceCents: number;
        lineTotalCents: number;
        taxRate?: number | null;
        id?: string | null;
      }[]
    | null;
  total: number;
  subtotalCents?: number | null;
  deliveryCents?: number | null;
  totalCents?: number | null;
  currency?: 'PLN' | null;
  deliveryMethod?: string | null;
  deliveryLabel?: string | null;
  deliveryKind?: ('courier' | 'pickup_point' | 'pickup') | null;
  /**
   * Punkt wpisany ręcznie przez klienta; brak integracji i weryfikacji przewoźnika.
   */
  pickupPointId?: string | null;
  pickupPointName?: string | null;
  pickupPointAddress?: string | null;
  deliveryBaseCents?: number | null;
  paymentSurchargeCents?: number | null;
  freeShippingThresholdCents?: number | null;
  freeShippingApplied?: boolean | null;
  /**
   * Puste w starszych zamówieniach = płatność online.
   */
  paymentMethod?: ('online' | 'bank_transfer' | 'cod') | null;
  paymentLabel?: string | null;
  reservationMinutes?: number | null;
  status?: ('new' | 'paid' | 'shipped' | 'cancelled' | 'expired') | null;
  paymentStatus?: ('pending' | 'paid' | 'failed' | 'cancelled' | 'expired') | null;
  paymentReviewRequired?: boolean | null;
  stockReleased?: boolean | null;
  idempotencyKey?: string | null;
  fingerprint?: string | null;
  accessTokenHash?: string | null;
  expiresAt?: string | null;
  paidAt?: string | null;
  shippedAt?: string | null;
  codCollectedAt?: string | null;
  privacyAccepted: boolean;
  termsAccepted: boolean;
  consentVersion?: string | null;
  mode?: 'test' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts".
 */
export interface PaymentAttempt {
  id: number;
  order: number | Order;
  provider: string;
  reference?: string | null;
  amountCents?: number | null;
  currency?: 'PLN' | null;
  status?: ('pending' | 'paid' | 'failed' | 'cancelled' | 'expired') | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events".
 */
export interface PaymentEvent {
  id: number;
  eventKey?: string | null;
  attempt: number | PaymentAttempt;
  digest?: string | null;
  outcome: 'paid' | 'failed' | 'cancelled';
  accepted?: boolean | null;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Skrzynka testowa. Wiadomości nie są wysyłane do odbiorców.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox".
 */
export interface Outbox {
  id: number;
  deduplicationKey: string;
  recipient: string;
  subject: string;
  body: string;
  status?: 'captured' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  privacyAccepted: boolean;
  consentVersion?: string | null;
  status?: ('new' | 'contacted' | 'closed') | null;
  contextKind?: ('product' | 'trip') | null;
  contextID?: number | null;
  contextTitle?: string | null;
  contextPath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: number;
  email: string;
  status?: ('pending' | 'active' | 'unsubscribed') | null;
  confirmationTokenHash?: string | null;
  unsubscribeTokenHash?: string | null;
  confirmationExpiresAt?: string | null;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  consentVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  reason?: string | null;
  published?: boolean | null;
  legacyKey?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  importedAt?: string | null;
  sourceUpdatedAt?: string | null;
  legacyPath?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: number;
  runKey: string;
  sourceManifestHash: string;
  status?: ('running' | 'complete' | 'failed' | 'needs-review') | null;
  sourceType?: string | null;
  counts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  unresolved?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  finishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actor: number | User;
  targetCollection: string;
  targetId: number;
  command: string;
  beforeStatus?: string | null;
  afterStatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'operations';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Wyłącznie publiczne materiały do pobrania. Dokumenty klienta i dane prywatne nie trafiają do tej kolekcji.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  legacyKey?: string | null;
  legacyPath?: string | null;
  sourceHash?: string | null;
  importRun?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-sessions';
        value: number | CourseSession;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'trips';
        value: number | Trip;
      } | null)
    | ({
        relationTo: 'albums';
        value: number | Album;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'signups';
        value: number | Signup;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payment-attempts';
        value: number | PaymentAttempt;
      } | null)
    | ({
        relationTo: 'payment-events';
        value: number | PaymentEvent;
      } | null)
    | ({
        relationTo: 'outbox';
        value: number | Outbox;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'import-runs';
        value: number | ImportRun;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  searchText?: T;
  vmId?: T;
  slug?: T;
  category?: T;
  categories?: T;
  categoryName?: T;
  manufacturer?: T;
  sku?: T;
  priceCents?: T;
  salePriceCents?: T;
  taxRate?: T;
  price?: T;
  salePrice?: T;
  stock?: T;
  images?: T;
  short?: T;
  body?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        label?: T;
        sku?: T;
        legacyKey?: T;
        priceCents?: T;
        stock?: T;
        image?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  featured?: T;
  warranty?: T;
  published?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  importedAt?: T;
  sourceUpdatedAt?: T;
  legacyPath?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  vmId?: T;
  parent?: T;
  image?: T;
  order?: T;
  published?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  importedAt?: T;
  sourceUpdatedAt?: T;
  legacyPath?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  org?: T;
  level?: T;
  maxDepth?: T;
  nextDate?: T;
  price?: T;
  minAge?: T;
  lead?: T;
  body?: T;
  image?: T;
  gallery?: T;
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  includes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  published?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  importedAt?: T;
  sourceUpdatedAt?: T;
  legacyPath?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-sessions_select".
 */
export interface CourseSessionsSelect<T extends boolean = true> {
  title?: T;
  course?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  priceCents?: T;
  capacity?: T;
  reserved?: T;
  published?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  importedAt?: T;
  sourceUpdatedAt?: T;
  legacyPath?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  kind?: T;
  lead?: T;
  body?: T;
  image?: T;
  album?: T;
  publishedAt?: T;
  listing?: T;
  listingCategory?: T;
  listingProducts?: T;
  listingMissing?:
    | T
    | {
        title?: T;
        legacyPath?: T;
        id?: T;
      };
  listingFrom?: T;
  listingTo?: T;
  listingTotal?: T;
  listingLinks?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  published?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  importedAt?: T;
  sourceUpdatedAt?: T;
  legacyPath?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips_select".
 */
export interface TripsSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  location?: T;
  startsAt?: T;
  endsAt?: T;
  priceCents?: T;
  lead?: T;
  body?: T;
  image?: T;
  album?: T;
  published?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  importedAt?: T;
  sourceUpdatedAt?: T;
  legacyPath?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  description?: T;
  date?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  published?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  importedAt?: T;
  sourceUpdatedAt?: T;
  legacyPath?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  path?: T;
  body?: T;
  courseSession?: T;
  trip?: T;
  published?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  importedAt?: T;
  sourceUpdatedAt?: T;
  legacyPath?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signups_select".
 */
export interface SignupsSelect<T extends boolean = true> {
  course?: T;
  session?: T;
  privacyAccepted?: T;
  consentVersion?: T;
  reservationExpiresAt?: T;
  confirmationTokenHash?: T;
  deduplicationKey?: T;
  emailConfirmedAt?: T;
  reservationReleased?: T;
  courseName?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  customerName?: T;
  email?: T;
  phone?: T;
  address?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        sku?: T;
        variantId?: T;
        variant?: T;
        qty?: T;
        price?: T;
        unitPriceCents?: T;
        lineTotalCents?: T;
        taxRate?: T;
        id?: T;
      };
  total?: T;
  subtotalCents?: T;
  deliveryCents?: T;
  totalCents?: T;
  currency?: T;
  deliveryMethod?: T;
  deliveryLabel?: T;
  deliveryKind?: T;
  pickupPointId?: T;
  pickupPointName?: T;
  pickupPointAddress?: T;
  deliveryBaseCents?: T;
  paymentSurchargeCents?: T;
  freeShippingThresholdCents?: T;
  freeShippingApplied?: T;
  paymentMethod?: T;
  paymentLabel?: T;
  reservationMinutes?: T;
  status?: T;
  paymentStatus?: T;
  paymentReviewRequired?: T;
  stockReleased?: T;
  idempotencyKey?: T;
  fingerprint?: T;
  accessTokenHash?: T;
  expiresAt?: T;
  paidAt?: T;
  shippedAt?: T;
  codCollectedAt?: T;
  privacyAccepted?: T;
  termsAccepted?: T;
  consentVersion?: T;
  mode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts_select".
 */
export interface PaymentAttemptsSelect<T extends boolean = true> {
  order?: T;
  provider?: T;
  reference?: T;
  amountCents?: T;
  currency?: T;
  status?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events_select".
 */
export interface PaymentEventsSelect<T extends boolean = true> {
  eventKey?: T;
  attempt?: T;
  digest?: T;
  outcome?: T;
  accepted?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox_select".
 */
export interface OutboxSelect<T extends boolean = true> {
  deduplicationKey?: T;
  recipient?: T;
  subject?: T;
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  privacyAccepted?: T;
  consentVersion?: T;
  status?: T;
  contextKind?: T;
  contextID?: T;
  contextTitle?: T;
  contextPath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  confirmationTokenHash?: T;
  unsubscribeTokenHash?: T;
  confirmationExpiresAt?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  consentVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  reason?: T;
  published?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  importedAt?: T;
  sourceUpdatedAt?: T;
  legacyPath?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  runKey?: T;
  sourceManifestHash?: T;
  status?: T;
  sourceType?: T;
  counts?: T;
  unresolved?: T;
  finishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actor?: T;
  targetCollection?: T;
  targetId?: T;
  command?: T;
  beforeStatus?: T;
  afterStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  legacyKey?: T;
  sourceHash?: T;
  importRun?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  legacyKey?: T;
  legacyPath?: T;
  sourceHash?: T;
  importRun?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Np. „Rozpocznij kurs nurkowania 07.09 lub 14.09 w Warszawie”
   */
  banner?: string | null;
  heroTitle?: string | null;
  heroText?: string | null;
  heroImage?: (number | null) | Media;
  priceGuarantee?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Tryb testowy: żadna metoda nie nadaje przesyłki ani nie pobiera stawek przewoźnika. Ceny wpisuje obsługa.
   */
  deliveryMethods?:
    | {
        key: string;
        label: string;
        priceCents: number;
        enabled?: boolean | null;
        /**
         * Puste pole w starszych wpisach działa jak kurier (adres wymagany).
         */
        kind?: ('courier' | 'pickup_point' | 'pickup') | null;
        /**
         * Tylko kurier i punkt odbioru. Wymaga włączenia pobrania w płatnościach testowych.
         */
        codAllowed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Puste = brak progu. Próg dotyczy wartości produktów; nie znosi dopłaty za pobranie.
   */
  freeShippingThresholdCents?: number | null;
  /**
   * Płatność online jest zawsze dostępna jako symulacja. Przelew i pobranie są wyłączone, dopóki nie zostaną tu jawnie włączone; status zmienia wyłącznie zalogowana obsługa z wpisem w historii operacji.
   */
  testPayments?: {
    bankTransferEnabled?: boolean | null;
    codEnabled?: boolean | null;
    /**
     * Wymagane po włączeniu przelewu lub pobrania: 60–20160 min (do 14 dni). Brak wartości wyłącza obie metody. Testy używają 2880 (48 h).
     */
    offlineReservationMinutes?: number | null;
    /**
     * Puste = bez dopłaty.
     */
    codSurchargeCents?: number | null;
  };
  nip?: string | null;
  facebook?: string | null;
  youtube?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  banner?: T;
  heroTitle?: T;
  heroText?: T;
  heroImage?: T;
  priceGuarantee?: T;
  phone?: T;
  email?: T;
  address?: T;
  deliveryMethods?:
    | T
    | {
        key?: T;
        label?: T;
        priceCents?: T;
        enabled?: T;
        kind?: T;
        codAllowed?: T;
        id?: T;
      };
  freeShippingThresholdCents?: T;
  testPayments?:
    | T
    | {
        bankTransferEnabled?: T;
        codEnabled?: T;
        offlineReservationMinutes?: T;
        codSurchargeCents?: T;
      };
  nip?: T;
  facebook?: T;
  youtube?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}